### ISSUE TITLE
Plugin proposal : Mutual Authentication for consumer

### ISSUE THREAD

**Issue by amramtamir** [Kong/kong#2048]
### Details

Just like key auth or other Auth methods, it will be great to have Mutual authentication as a plugin.
The use case is to protect a specific API by a consumer that will use MA.
The consumer will have to include a client certificate in the request to be allowed to consume the API.
On the API side , there are 2 directives that needs to be configured (This is how it is done in nginx) :

1. ssl_client_certificate -> path to CA to validate the request, for example : /etc/nginx/certs/ca/ca.crt;
2. ssl_verify_client (on | optional) -> allow\ deny unauthenticated requests .

Currently I am achieving this by specifying a custom nginx config with a "server" block.
The issue is that this "server" block is not part of Kong facilities.

**Comment by Tieske** [comment]
@amramtamir I don't think this will be added on short notice, so maybe you can share your configuration for others to learn/copy from? Thx!

**Comment by ewilde** [comment]
@Tieske @thefosk We are super excited about this feature, we have a lot of use cases for mutual ssl authentication and would love to do it using our kong setup. I've made a stab at how it might look

![image](https://cloud.githubusercontent.com/assets/329397/24408136/c22da8f6-13c4-11e7-9a90-93920efd6e1c.png)

1. Client calls a kong endpoint supplying a client certificate
```
curl https://api.com/service \
    -H "Content-Type: application/vnd.api+json" \
   --key ./bob@acme.com.key.pem  \
   --cert ./bob@acme.com.cert.pem  \
   --cacert ./acme.com.ca-chain.cert.pem
```
2. If the client certificate is verified:
  * Using the certificate subject [$ssl_client_s_dn](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables) lookup the kong consumer

3. Call upstream api with [upstream headers](https://getkong.org/plugins/key-authentication/#upstream-headers)

## Configuring the proposed plugin
### Configure updated certificates endpoint
Upload server and client certificates
```
curl -X POST http://localhost:8001/certificates \
    -d "cert=@/path/to/cert.pem" \
    -d "key=@/path/to/cert.key" \
    -d "client_certificate=@/path/to/certificate.authorities.pem \
    -d "snis=ssl-example.com,other-ssl-example.com"
```
| form parameter  | default | description |
| ------------- | ---| ------------- |
| [client_certificate](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_client_certificate)  |  | Specifies a file with trusted CA certificates in the PEM format used to verify client certificates. Note you can include more than one certificate in this file, just append them all together |

### Enable the ssl-auth plugin
This is a new plugin to allow verified users to access apis, in a similar manner to the existing [key-auth](https://getkong.org/plugins/key-authentication/) plugin 
```
$ curl -X POST http://kong:8001/apis/{api}/plugins \
    --data "name=ssl-auth"
```
### Create the api endpoint
```
 curl -i -X POST http://localhost:8001/apis \
    -d "name=ssl-api" \
    -d "upstream_url=http://my-api.com" \
    -d "hosts=ssl-example.com,other-ssl-example.com"
    -d "https_only=true"
    -d "verify_client=on"
    -d "verify_depth=2"
```
| form parameter  | default | description |
| ------------- | ---| ------------- |
| [verify_client](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client)  | false | if `true`; will only allow clients that present a certificate signed by a certificate authority which is present in the configured `client_certificate`  |
| [verify_depth](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_depth) | 1 | Sets the verification depth in the client certificates chain. |

### Create a consumer
```
curl -X POST http://kong:8001/consumers/ \
    --data "username=simon"
```

### Create a client certificate entry
Create an client certificate entry that allow a consumer access
```
curl -X POST http://kong:8001/consumers/{consumer}/ssl-auth -d 'ssl_client_s_dn=C=GB, ST=England, O=Acme Limited, OU=Acme Web Services, CN=Bob Smith/emailAddress=bob.smith@acme.com'
HTTP/1.1 201 Created

{
    "consumer_id": "876bf719-8f18-4ce5-cc9f-5b5af6c36007",
    "created_at": 1443371053000,
    "id": "62a7d3b7-b995-49f9-c9c8-bac4d781fb59",
    "client_subject": "C=GB, ST=England, O=Acme Limited, OU=Acme Web Services, CN=Bob Smith/emailAddress=bob.smith@acme.com"
}
```
| form parameter  | default | description |
| ------------- | ---| ------------- |
| client_subject | | the “subject DN” string of the client certificate for an established SSL connection. In nginx this is stored in the [$ssl_client_s_dn](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables) variable for validated clients |

### Related issues:
https://github.com/Mashape/kong/issues/740
https://github.com/Mashape/kong/issues/1194
https://github.com/Mashape/kong/issues/421

**Comment by amramtamir** [comment]
@ewilde - Cool!! Super useful! I am waiting for it, the stub looks great. 👍  
I have also implemented something similar to the work around you have offered, but with Kong's facilities enabled.
I am using docker, and in my entrypoint script I am replacing all the placeholders and remarks.

       server { 
        listen        0.0.0.0:-PORT- ssl;
        server_name -SERVER_NAME-;
        ssl_certificate      -cer-;
        ssl_certificate_key  -key-;
        #ssl_client_certificate -ca-;
        #ssl_verify_client optional;
        #ssl_trusted_certificate -ca-;
        #ssl_verify_depth 2;
        error_page 404 408 411 412 413 414 417 /kong_error_handler;
        error_page 500 502 503 504 /kong_error_handler;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

        location / {
            set $upstream_host nil;
            set $upstream_url nil;

            access_by_lua_block {
                kong.access()
            }

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Client-Dn $ssl_client_s_dn;
            proxy_pass_header Server;
            proxy_pass $upstream_url;

            header_filter_by_lua_block {
                kong.header_filter()
            }

            body_filter_by_lua_block {
                kong.body_filter()
            }

            log_by_lua_block {
                kong.log()
            }
    }

        location = /kong_error_handler {
            internal;
            content_by_lua_block {
                require('kong.core.error_handlers')(ngx)
            }
        }
    }

**Comment by ewilde** [comment]
@amramtamir thanks for posting your nginx config, very helpful. Does this setup pass look up the kong consumer and pass on the upstream headers like `X-Consumer-ID` etc...?

**Comment by amramtamir** [comment]
Haven't checked , though I believe its not because there is no consumer configured on Kong's side.
Also this implementation is per proxy meaning that its less generic when you have multiple APIs with different MA settings.
This why a plugin is more than helpful to fulfill this requirement. :)

**Comment by ewilde** [comment]
@amramtamir I agree we would really benefit from this plugin. @Tieske @thefosk does this plugin proposal look reasonable to you?

**Comment by flyabc** [comment]
@ewilde @amramtamir Hi , I also encountered ssl mutual authentication problem and I read this issue carefully,but I still do not know how to achieve mutual authentication, I want to say my question,Can you take the time to help me?
1,Why can not I find **Ssl-auth** plugin ?
2, Why can not I add a API with the verify_client  or verify_depth property ?
      curl -i -X POST http://localhost:8001/apis \
      -d "name=ssl-api"  \
     -d "upstream_url=http://my-api.com" \
    -d "hosts=ssl-example.com,other-ssl-example.com" \
    -d "verify_client=on" \
    -d "verify_depth=2" 

then I got some message:
**{"verify_depth":"verify_depth is an unknown field","verify_client":"verify_client is an unknown field"}**

3，Why can not I create a certificate with **client_certificate** property ？
   curl -i -X POST http://localhost:8001/certificates \
    -d "cert=@/path/to/cert.pem" \
    -d "key=@/path/to/cert.key" \
    -d "client_certificate=@/path/to/certificate.authorities.pem` \
    -d "snis=ssl-example.com"
then the message:
**{"client_certificate":"client_certificate is an unknown field"}**

4,What configuration files do I need to change ? My configuration file content is not the same as yours
**My kong version is 0.10.1,not the enterprise version.**

**Comment by ewilde** [comment]
@flyabc this is just a proposal for a `new` plugin, the feature does as described does not exist. Good to know that other people would value this. Unfortunately I don't have the necessary lua and nginx skills to implement this myself - hopefully I can help with the specification and testing of this feature

**Comment by flyabc** [comment]
@ewilde thank you very much,I will try to find anther ways.

**Comment by mwaaas** [comment]
am willing to learn lua to work on this, is anyone working on it

**Comment by mwaaas** [comment]
@ewilde In the proposed plugin which variable should be used in the client certificate to be matched to the consumer.

**Comment by ewilde** [comment]
@mwaaas in the proposal `client_subject` would be used to match the certificate to the consumer. So the plugin would extract the certificates subject and look for a consumer with a matching `client_subject`. I'll update the proposal to highlight that

**Comment by egobsv** [comment]
@ewilde has there been any progress on this idea. I see that your solution already passes the client variables using:

proxy_set_header   X-SSL-Client-DN         $ssl_client_s_dn;

On the other hand, the problem I am trying to solve is that I don't want my internal APIs to implement this user logic. I would like to have a transparent mutual TLS authentication mechanism, where Kong would check whether the incoming client certificate is revoked/disabled using:
 
ssl_stapling_verify on;

My use case requires that his works for every incoming requests, regardless of which of our internal API the request is for. With that in mind I am contemplating opening another issue under mutual TLS, what do you think?

**Comment by AlexProfi** [comment]
I get 302 redirect always even if I switch ssl-redirect: "false"

**Comment by bungle** [comment]
This is now implemented as `mtls-auth` plugin in Kong Enterprise. Third-party plugins could do the same as the basis of this is implemented in OSS.
