### ISSUE TITLE
high CPU after upgrade to version 2.1.3

### ISSUE THREAD

**Issue by huangyonghome** [Kong/kong#6347]
Kong cluster (2 nodes,version:1.x) worked very well on our production environment..Last week We had to upgrade the kong version to support the `request-transformer` plugin which help us  rewrite the request URL .

following below official document , we upgraded the both two Kong nodes from 1.x to the latest version 2.1.3 
https://docs.konghq.com/2.1.x/upgrading/

Meanwhile, we added the `request-transformer` plugins under a routes.

But after a couple days of upgrade,The Kong nodes CPU goes from 8%( old kong cluster CPU utilization)  to 100%.

below is the CPU utilization:
![image](https://user-images.githubusercontent.com/40015415/93320938-3c382b00-f844-11ea-8431-edc4e1847396.png)

below is the input of command `sudo strace -t -T -v -f -p 23705` (23705 is the pid of Nginx)
![image](https://user-images.githubusercontent.com/40015415/93321101-6a1d6f80-f844-11ea-8bf5-3e4255ad2d8c.png)

kong.conf:
```
prefix = /data/logs/kong/       # Working directory. Equivalent to Nginx's
proxy_access_log = access.log       # Path for proxy port request access
proxy_error_log = error.log         # Path for proxy port request error
admin_access_log = admin_access.log # Path for Admin API request access
admin_error_log = admin_error.log         # Path for Admin API request error
admin_listen = 0.0.0.0:8001     # Address and port on which Kong will expose
trusted_ips = 0.0.0.0/0,::/0
real_ip_header = X-Forwarded-For
database = postgres             # Determines which of PostgreSQL or Cassandra
pg_host = 10.111.30.210             # The PostgreSQL host to connect to
pg_port = 5432                  # The port to connect to.
pg_user = kong                  # The username to authenticate if required.
pg_password = kong                 # The password to authenticate if required.
pg_database = kong              # The database name to connect to.
pg_ssl = off                    # Toggles client-server TLS connections
pg_ssl_verify = off             # Toggles server certificate verification if
cluster_listen = 0.0.0.0:7946   # Address and port used to communicate with
cluster_listen_rpc = 127.0.0.1:7373  # Address and port used to communicate
```

nginx.conf:

```
[work@dwd-kong-node5 kong]$ cat /usr/local/kong/nginx.conf
pid pids/nginx.pid;
error_log error.log notice;

# injected nginx_main_* directives
daemon off;
worker_processes auto;
worker_rlimit_nofile 16384;

events {
    # injected nginx_events_* directives
    multi_accept on;
    worker_connections 16384;
}

http {
    include 'nginx-kong.conf';
}
```

- Kong version (2.1.3)
- Operating system (Centos 7.6)
- hardware:  both tow nodes: 2c4G 

Could you please help me for this issue? any helps are very appreciated!

Thank you very much

**Comment by kikito** [comment]
Hello, it is very difficult to diagnose what might be happening in your setup with the info you gave us.

There's a similar issue (#6331) which was fixed recently (#6300). It seemed to occur when `kong reload`. Could this be what's happening in your system?

**Comment by huangyonghome** [comment]
> Hello, it is very difficult to diagnose what might be happening in your setup with the info you gave us.
> 
> There's a similar issue (#6331) which was fixed recently (#6300). It seemed to occur when `kong reload`. Could this be what's happening in your system?

Thank you ! But It is a little different, The Cpu utilization of Kong server increases to 100% after running several days..I manually restart kong services ,the cpu usage goes down to about 3%. But this problem happens again after days . 
I didn't reload or restart kong .

**Comment by huangyonghome** [comment]
I got some clues.
I received an alert at 0:00 today that CPU usage grew up tp 100% again. I checked the `message` logs and found  somethings:

```
Sep 17 23:59:01 dwd-kong-node5 systemd: Reloading kong service.
Sep 17 23:59:02 dwd-kong-node5 kong: 2020/09/17 23:59:02 [warn] ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Sep 17 23:59:02 dwd-kong-node5 systemd: Reloaded kong service.
Sep 17 23:59:02 dwd-kong-node5 kong: Kong reloaded
```

I have an logrotate job running at specified time, This script will reload kong service at 0.00 AM

But, I still don't know how to resolve this issue ?

**Comment by jeremyjpj0916** [comment]
> I have an logrotate job running at specified time, This script will reload kong service at 0.00 AM

100% chance if your ever running kong reload in your environment you will hit this issue I think, have you given 2.1.4 a shot(just released)?

**Comment by huangyonghome** [comment]
> > I have an logrotate job running at specified time, This script will reload kong service at 0.00 AM
> 
> 100% chance if your ever running kong reload in your environment you will hit this issue I think, have you given 2.1.4 a shot yet(just released)?

Thanks for your reply.Has this problem been solved in 2.1.4 ?

**Comment by jeremyjpj0916** [comment]
I think so, I just started running it and confirmed it is fixed there for me.

**Comment by huangyonghome** [comment]
> I think so, I just started running it and confirmed it is fixed there for me.

Thank you , I prefer to observe for a period of time.As a temporary solution,I use the command `systemctl restart kong`,instead of `kong reload`. bcz I wanna find out if this is really caused by `Kong reload`

**Comment by jeremyjpj0916** [comment]
Sure, I ran their patch fix for 2 days letting my automated reload script execute too and it had no issues. As always test in dev/stage and don’t take it to prod until you have confidence.

**Comment by huangyonghome** [comment]
> Sure, I ran their patch fix they put in 2.1.4 on 2.1.3 for 2 days letting my automated reload script execute too and it had no issues. As always test in dev/stage and don’t take it to prod until you have confidence.
Thank you . I am going to schedule an upgrade from 2.1.3 to 2.1.4 on prod if the high CPU issue disappears next week

**Comment by bungle** [comment]
We fixed this in two places:
First: https://github.com/Kong/kong/pull/6300
Second: https://github.com/Kong/lua-resty-worker-events/pull/37

**Comment by hishamhm** [comment]
@huangyonghome Looks like this was fixed in 2.1.4. If the issue persists with 2.1.4, feel free to reopen! Thank you!
