### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'dump_info'

### ISSUE THREAD

**Issue by mpromny** [Kong/kong#7460]
### Summary
- Kong version (`2.4`) - customized
- external plugins - Python
- Unable to start each plugin as a microservice
      - unable to migrate from old approach (single process for many plugins) to the new one (each plugin has his own server)
      - I'm able to load those plugins using "single server"

### Steps To Reproduce

1. Create docker image
```
ARG KONG_BASE=kong:2.4

FROM ${KONG_BASE}
ENV PATH="/home/kong/.local/bin:${PATH}"

USER root
RUN apk update
RUN apk add python3 python3-dev make git g++ gcc libc-dev libffi-dev

USER kong
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install kong-pdk

USER root
RUN pip3 install kong-pdk

RUN cp /home/kong/.local/bin/* /usr/local/bin/
RUN chmod 777 /usr/local/bin/* && chown kong /usr/local/bin/*

USER kong
```
2. Load plugins as configmap via helm or add directly to the docker image
   - I used py-hello plugin
   - Example has been slightly modified: 
     py-hello plugin:
        Line 19:
               From: ` def access(self, kong: kong.kong):`
               To: ` def access(self, kong: kong):`
   
3. Modify kong configuration 
```
  plugins: bundled, py-hello
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/py.socket
  pluginserver_py_start_cmd: /opt/test/py-hello.py
  pluginserver_py_query_cmd: /opt/test/py-hello.py -d
```

4. Use helm to deploy service

### Additional Details & Logs
- Error:
```
Traceback (most recent call last):
File "/opt/test/py-hello.py", line 33, in <module>
start_dedicated_server("py-hello", Plugin, version, priority)
File "/home/kong/.local/lib/python3.8/site-packages/kong_pdk/cli.py", line 95, in start_dedicated_server
args = parse(dedicated=True)
File "/home/kong/.local/lib/python3.8/site-packages/kong_pdk/cli.py", line 51, in parse
if (not args.dump_info and not args.dump_all_info) and not os.path.exists(args.prefix):
AttributeError: 'Namespace' object has no attribute 'dump_info

2021/06/16 13:07:00 [error] 1#0: init_by_lua error: ...al/share/lua/5.1/kong/runloop/plugin_servers/process.lua:159: Not a plugin info table:
/opt/test/py-hello.py -d`
```
- Plugin used for tests:
  [py-hello](https://github.com/Kong/kong-python-pdk/blob/master/examples/py-hello.py)
- Kong configuration:
```
  plugins: bundled, py-hello
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/py.socket
  pluginserver_py_start_cmd: /opt/test/py-hello.py
  pluginserver_py_query_cmd: /opt/test/py-hello.py -d
```
- Operating system
  Kubernetes:
    - Version: v1.19.11
    - OS-IMAGE: Ubuntu 20.04.2 LTS
    - KERNEL-VERSION: 5.4.0-1045-aws
  
- Helm configuration:
```
  userDefinedVolumes:
  - name: py-scripts
    configMap:
      name: py-scripts
      defaultMode: 0777
      items:
        - key: py-hello
          path: py-hello
        - key: py-test
          path: py-test
  userDefinedVolumeMounts:
    - name: py-scripts
      mountPath: /opt/test/py-hello.py
      subPath: py-hello
    - name: py-scripts
      mountPath: /opt/test/py-test.py
      subPath: py-test

---
```
- Working configuration - single server
```

  plugins: bundled, py-hello, py-test
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/python_pluginserver.sock
  pluginserver_py_start_cmd: kong-python-pluginserver -kong-prefix /usr/local/kong/ -plugins-directory /opt/test
  pluginserver_py_query_cmd: kong-python-pluginserver -dump-all-plugins -plugins-directory /opt/test

```
>

**Comment by fffonion** [comment]
I think this is indeed a bug since some version of Python 3.x changed the behaviour. I will address a PR.

**Comment by fffonion** [comment]
It's now fixed in 0.2.4 kong-python-pdk.

**Comment by mpromny** [comment]
@fffonion 
Thank you for responding so quickly and your fix, I really appreciate that.

Current status:
- I'm able to start each plugin as a "microservice" but my kong stopped to work when I use those plugins.  Do you have an idea what it could be?

Please find below some details:
```
PLUGIN:
    #!/usr/bin/env python3

    Schema = (
        { "message": { "type": "string" } },
    )

    version = '0.1.0'
    priority = 0

    class Plugin(object):
      pass

    if __name__ == "__main__":
        from kong_pdk.cli import start_dedicated_server
        start_dedicated_server("py-hello", Plugin, version, priority)
---
Loaded to Kong as:

apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: py-hello
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
  config:
plugin: py-hello

---

- I tired db-less and declarative approach
    - db-less
           - unable to display services/routes/plugins via kong-admin    
           - some errors in logs
    - declarative
           - able to display configuration vi kong-admin 
           - unable to find any errors

DB-LESS logs:
plugins.lua:126 DEPRECATED: /plugins/schema/:name endpoint is deprecated, please use /schemas/plugins/:name instead., client: 127.0.0.1, server: kong_admin, request: "GET /plugins/schema/py-test HTTP/1.1", host: "localhost:8001"
127.0.0.1 - - [17/Jun/2021:07:00:11 +0000] "GET /plugins/schema/py-test HTTP/1.1" 404 39 "-" "Go-http-client/1.1"


level=error msg="failed to fill-in defaults for plugin: py-test" component=controller
level=error msg="failed to update kong configuration: posting new config to /config: HTTP status 400 (message: \"declarative config is invalid: {plugins={{name=\\\"plugin 'py-test' not enabled; add it to the 'plugins' configuration property\\\"}}}\")" component=controller
level=error msg="failed to sync: posting new config to /config: HTTP status 400 (message: \"declarative config is invalid: {plugins={{name=\\\"plugin 'py-test' not enabled; add it to the 'plugins' configuration property\\\"}}}\")" component=sync-queue

```

**Comment by fffonion** [comment]
HI @mpromny, as the last error message suggested, you will need to add the `py-test`
plugin to `plugins` configuration of Kong.

```
plugins: bundled, py-hello
```

needs to be 

```
plugins: bundled, py-hello, py-test
```

**Comment by mpromny** [comment]
Hi @fffonion 
Yes, you are right. Sorry for the confusion, that was my oversight. Unfortunately, after I fixed that, the problem still exists for db-Less and declarative configurations:
- no errors
- I'm able to check configuration via kong-api
- sometimes first request can be processed - just after Deployment restart (I'm guessing that Kong didn't mange to start those plugins)

Maybe I should use different image and test it on Ubuntu?

**Comment by fffonion** [comment]
@mpromny Try turn on debug loggin on both sides, for kong `log_level: debug` and for python-pdk `pluginserver_py_start_cmd: /opt/test/py-hello.py -vvv`. This will also help verify if Kong has invoked
the external plugin or not. The output of the external plugin will be visible in Kong's error log, with prefix
of `[py]` in your case.

Generally Kong will stop and start the external plugins if you configure `_start_cmd`, but there could be an unexpected
bug that Kong doesn't properly restart it.

**Comment by mpromny** [comment]
@fffonion 
Unfortunately, nothing.

**Comment by mpromny** [comment]
@fffonion 
Thank you for your help, I think that I found the problem and a solution/workaround

Please find below the details:

### Introduction:

`log_level: debug` - has been already set
`pluginserver_py_start_cmd: /opt/test/py-hello.py -vvv` - has been added

Kong:
```
2021/06/17 14:14:28 [debug] 1#0: [lua] plugins.lua:245: load_plugin(): Loading plugin: grpc-gateway
2021/06/17 14:14:28 [debug] 1#0: [kong] process.lua:62 search config for pluginserver named: py
2021/06/17 14:14:28 [debug] 1#0: [kong] mp_rpc.lua:19 mp_rpc.new: /usr/local/kong/py.sock
2021/06/17 14:14:29 [debug] 1#0: [lua] plugins.lua:245: load_plugin(): Loading plugin: py-hello
2021/06/17 14:14:29 [debug] 1#0: [lua] plugins.lua:245: load_plugin(): Loading plugin: jwt
```

An interesting finding:

- Kong restart
  - kong-api shows that plugin has been loaded (please find above posted logs)
  - no errors   
- 1st request 
   - it was processed but
   ```
   [crit] 30#0: *120 connect() to unix:/usr/local/kong/py.socket failed (2: No such file or directory), client: 100.96.4.0, server: kong, request: "GET /foo HTTP/1.1", host: "kong-test.staging.k8s.example.com"
   [error] 30#0: *120 [kong] mp_rpc.lua:181 [py-hello] trying to connect: no such file or directory, client: 100.96.4.0, server: kong, request: "GET /foo HTTP/1.1", host: "kong-test.staging.k8s.example.com"
   [crit] 30#0: *120 connect() to unix:/usr/local/kong/py.socket failed (2: No such file or directory), client: 100.96.4.0, server: kong, request: "GET /foo HTTP/1.1", host: "kong-test.staging.k8s.example.com"
   [error] 30#0: *120 [kong] mp_rpc.lua:181 [py-hello] trying to connect: no such file or directory, client: 100.96.4.0, server: kong, request: "GET /foo HTTP/1.1", host: "kong-test.staging.k8s.example.com"
   [error] 30#0: *120 [kong] mp_rpc.lua:308 [py-hello] no such file or directory, client: 100.96.4.0, server: kong, request: "GET /foo HTTP/1.1", host: "kong-test.staging.k8s.example.com"
   [debug] 30#0: *120 [lua] init.lua:955: balancer(): setting address (try 1): 100.96.9.2:8080
   [debug] 30#0: *120 [lua] init.lua:984: balancer(): enabled connection keepalive (pool=100.96.9.2|8080, pool_size=60, idle_timeout=60, max_requests=100)
   "GET /foo HTTP/1.1" 200 1499 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
   ```    

      -  `py-hello` plugin hasn't been used (no additional custom http headers in response)
      
- 2nd request 
   - no response (http 503 gateway timeout)
   - not even a trace in logs
   
### Issue:

Plugin configuration:
```
  plugins: bundled, py-hello
  pluginserver_names: py

  pluginserver_py_socket: /usr/local/kong/py.socket
  pluginserver_py_start_cmd: /plugins/py-hello.py -vvv
  pluginserver_py_query_cmd: /plugins/py-hello.py -dump
```
  
Error from the log: 
`to unix:/usr/local/kong/py.socket failed (2: No such file or directory),`  

What we have on POD:
`srwxr-xr-x    1 kong     nogroup          0 Jun 17 15:00 py_hello.sock`

 Issue:
 Plugin doesn't use value which has been set in `pluginserver_py_socket:`
 
 ### Solution:
Configure: `pluginserver_py_socket: /usr/local/kong/py_hello.sock`  (plugin name where all hyphens have to be converted to underscores)

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team
